vport: Fix strncpy warning
g++-8.2.0 complains about strncpy with the following warning:

```
drivers/vport.cc: In member function ‘CommandResponse VPort::Init(const bess::pb::VPortArg&)’:
drivers/vport.cc:508:12: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 16 equals destination size [-Werror=stringop-truncation]
     strncpy(ifname_, name().c_str(), IFNAMSIZ);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/vport.cc:506:12: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 16 equals destination size [-Werror=stringop-truncation]
     strncpy(ifname_, arg.ifname().c_str(), IFNAMSIZ);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Error: drivers/vport.o
```

Fix the usage of strncpy with an explicit null termination. This was not
a problem for arg.ifname(), because the code checks the length
immediately above, but the compiler is not smart enough to understand
that.